##
## Makefile for  in /home/exam/rendu/ex_1
## 
## Made by Exam User
## Login   <exam@epitech.net>
## 
## Started on  Fri Feb 19 09:09:40 2016 Exam User
## Last update Fri Feb 19 09:12:01 2016 Exam User
##

all:
	gcc -o half_str half_str.c
clean:
	rm -rf half_str

re: clean all
